# -*- coding: utf-8 -*-
"""thulasi doss.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TBNmitmTRs9P803FFPLBTRWRFtPFZDrH
"""

#Copy this text below. See if you can do it with just the one print statement!
print("""I am signing up for Replit's 100 days of Python challenge! I will make sure to spend
some time every day coding along, for a minimum of 10 minutes a day. I'll be using
Replit, an amazing online IDE so I can do this from my phone wherever I happend to be.
No excuses for not coding from the middle of a field!""")

#ii) Crete a dictionary for malware and description. And perform all the dictionary
malware={'adwar':'tracks user activity',
        'Botnet':'infected and commanded by the attacker',
        'keylogger':'A keylogger can monitor a great deal of user activity, including email, browsing activity, program ',
        'spyware':'A little like adware'}
print(malware)
print(len(malware))
print(type(malware))
malware['trojon']='trojon is a malware it attack unexpeted time'
print(malware)
malware.update({'adwar': 'virus'})
print(malware)
malware.pop('spyware')
print(malware)
malware.clear()
print(malware)

#2
print("A person bought a mobile for the cost of 12,300 with additionally he pays 18% of GST.")
price=12300
GST=price*(18/100)
NetPrice=price+GST
print("GST",GST)
print("NetPrice:",NetPrice)

#3) Create a dataset for cybercrime, respective to IPC Section, offence and penalties
import pandas as pd
cybercrime=pd.DataFrame({
    'offence':['email abuse','online drugs','online of arms sale','cyber fraud','web hacking'],
    'ipc section':['sec.500','NDPS','Arms Act 1959','sec.420','sec.383'],
    'penalities':['2000rs','3000rs','3000rs','2500rs','5000rs']
})
print(cybercrime)
cybercrime['Category']=cybercrime["ipc section"].apply(lambda x: "social crime" if x=='sec.383' or x=='NDPS' or x=='Arms Act 1959' else "abuse crime" )
print(cybercrime)

#4
import pandas as pd
student=pd.DataFrame({'name':['thulasi','doss','aswin','ashok','ram','kumar','hari','vicky','jai','shankar'],
                      'dob':[2000,2002,2001,2003,2001,2000,2001,2002,2001,2000],
                      'weight':[45,50,76,87,55,43,60,90,65,76],
                      'height':[150,130,120,140,160,135,175,155,132,124]})
print(student)
student['age']=2022-student['dob']
student['BMI']=(student['weight'])/((0.01*student['height'])*2)
student['health']=student['BMI'].apply(lambda x: 'healthy' if x>30 and 40>x else 'not healthy')
print(student)

#5
def house():
 unit=int(input("Enter your unit: "))
 if(unit <= 100):
    bill = unit*0.05
 elif unit >= 101 and unit <= 200:
    bill = 5 + ((unit - 100) * 0.75)
 elif unit >= 201 and unit <= 300:
    bill = 5 + 75 + ((unit - 200) * 1.20)
 else:
    bill = 5 + 75 + 120 + ((unit - 300) * 1.50)
 print("Bill per unit:",bill)
print("House bill")
house()